### ISSUE TITLE
Missing file FormFactor.gwt.xml

### ISSUE THREAD

**Issue by mazzolini** [eemi2010/ext4j#1]
Module com.eemi.ext4j.Ext inherits com.emitrom.pilot.core.formfactor.FormFactor but file com/emitrom/pilot/core/formfactor/FormFactor.gwt.xml is missing

**Comment by eemi2010** [comment]
True. Looks like the build file missed it :(
Sorry for that. Will fix it asap.
In the meantime  create  com/emitrom/pilot/core/formfactor/FormFactor.gwt.xml  in your project with the following content.
Sorry again 

<?xml version="1.0" encoding="UTF-8"?>



<module>

```
<!-- Determine if we are in a phone, tablet or browser. -->
<define-property name="formfactor" values="desktop,tablet,phone" />
<collapse-property name="formfactor" values="*" />

<property-provider name="formfactor">
```

  <![CDATA[
      // Look for the formfactor as a url argument.
      var args = location.search;
      var start = args.indexOf("formfactor");
      if (start >= 0) {
        var value = args.substring(start);
        var begin = value.indexOf("=") + 1;
        var end = value.indexOf("&");
        if (end == -1) {
          end = value.length;
        }
        var toReturn = value.substring(begin, end);
        if(toReturn != 'desktop' && toReturn != 'phone' && toReturn != 'tablet'){
         toReturn = 'desktop';
        }
        return toReturn;
      }

```
  // Detect form factor from user agent.
  var ua = navigator.userAgent.toLowerCase();
  if (ua.indexOf("iphone") != -1 || ua.indexOf("ipod") != -1) {
    // iphone and ipod.
    return "phone";
  } else if (ua.indexOf("ipad") != -1) {
    // ipad.
    return "tablet";
  } else if (ua.indexOf("android") != -1 || ua.indexOf("phone") != -1) {
    /*
     * Android - determine the form factor of android devices based on the diagonal screen
     * size. Anything under six inches is a phone, anything over six inches is a tablet.
     */
    var dpi = 160;
    var width = $wnd.screen.width / dpi;
    var height = $wnd.screen.height / dpi;
    var size = Math.sqrt(width*width + height*height);
    return (size < 6) ? "phone" : "tablet";
  }

  // Everything else is a desktop.
  return "desktop";
```

  ]]>
    </property-provider>

</module>
