### ISSUE TITLE
Question about mixing Extjs and Ext4j

### ISSUE THREAD

**Issue by BartoszGalek** [eemi2010/ext4j#2]
Can Ext4j be used together on the same page that already uses extjs 4 components?
I know that GXT cannot, because there are reported JavaScript and css issues with that practice.

Cheers

**Comment by eemi2010** [comment]
Ext4j is based on Ext JS.
So you can use the JavaScript and CSS you already have in your project(Assuming you are using Ext JS 4+)
So the answer is Yes.
I will share a blog post soon about how to use use Ext4j in an existing Ext JS application.

Cheers

**Comment by BartoszGalek** [comment]
Thanks, that's great news.
I'm awaiting the blog post, please let me know when and where it will be awailable. I would love to see the example.

Cheers

**Comment by eemi2010** [comment]
Please have a look at https://github.com/eemi2010/ext4j/blob/master/gwt4ext/guide/guide.asciidoc#adding-ext4j-into-an-existing-ext-js-application.

I just added an entry in the user guide.

Cheers,

Alain

**Comment by BartoszGalek** [comment]
Thanks

**Comment by eemi2010** [comment]
Please let me know if it worked for you so we can close this issue.

**Comment by BartoszGalek** [comment]
It worked for me thanks, I'll let you know if I have other questions/issues.

Cheerio,
Bartosz

**Comment by eemi2010** [comment]
Please let me know how  you like the library so far.
Those feedback help me improve the tool.
Cheers.
Alain
